<Project Sdk="Microsoft.NET.Sdk">
<Sdk Name="Aspire.AppHost.Sdk" Version="13.0.2" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>dab13289-0cb1-4729-ad05-a3e52890b9f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Azure" />
    <PackageReference Include="Aspire.Hosting.Azure.CognitiveServices" />
    <PackageReference Include="Aspire.Hosting.Azure.AIFoundry" />
    <PackageReference Include="Aspire.Hosting.Azure.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.GitHub.Models" />
    <PackageReference Include="Azure.Provisioning.AppConfiguration" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../BuildWithAspire.ApiService/BuildWithAspire.ApiService.csproj" />
    <ProjectReference Include="../BuildWithAspire.Web/BuildWithAspire.Web.csproj" />
    <ProjectReference Include="../BuildWithAspire.McpServer/BuildWithAspire.MCPServer.csproj" />
    <ProjectReference Include="../BuildWithAspire.Abstractions/BuildWithAspire.Abstractions.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
